Doucmentation
se-edu/learningresources pull request #19
Opened 2017-02-18 05:03 UTC by kychua

Future work:
- tools for documentation
- process for writing documentation

2017-03-05 09:09 UTC, damithc commented
@kychua can you get this peer reviewed by someone?

2017-03-06 17:19 UTC, kychua commented
@wkurniawan07 can you please help me review this? Thanks!

2017-03-07 06:09 UTC, wkurniawan07 commented
Sure! Give me just a moment.

2017-03-08 08:23 UTC, wkurniawan07 requested changes
Great work in general! Good content and easy to follow.

You may also consider adding a section on documentation pitfalls/anti-patterns or how not to document. Of course it could be deferred to your next book chapter.

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +* Encourage others to use your software: ["If it isn't documented, it doesn't exist."](http://www.mikepope.com/blog/DisplayBlog.aspx?permalink=1680)
Could be better if formatted this way:
* **Main point**: explanation.

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +* [test](http://idratherbewriting.com/2015/07/07/testing-your-instructions/) your instructions
The link should wrap the entire "test your instructions" phrase.

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +This is known as [Readme Driven Development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html).
Structure it this way?
```markdown
A README ...
A good README...

For a good guide on ...
- Some suggest that ... This is known as ...
```

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +See [this](https://www.petrikainulainen.net/software-development/processes/writing-just-enough-documentation/) to learn more about what to include in a developer guide.
Add a break between "They should..." and "See this ...".

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +[Here](https://jacobian.org/writing/what-to-write/) is a useful guide on how to tackle different types of user documentation.
Add a break between "User guides can..." and "Here is a useful guide...".

2017-03-08 08:23 UTC, wkurniawan07 commented on contents/projectManagement/documentation.md
> +They include variable, method and class comments, as well as inline comments.
Consider rephrasing to:

They include **API documentation** for variables, methods, classes, and packages, as well as **inline comments**.

2017-03-15 13:53 UTC, kychua commented
@wkurniawan07 Thanks for the comments! I've updated the chapter, will do the section on documentation pitfalls next time.

2017-03-20 16:32 UTC, wkurniawan07 approved these changes
LGTM!

2017-03-27 14:21 UTC, damithc reviewed
Good work @kychua 
Some comments added. Revise as you see fit.
Adding more content and/or getting more peer reviews is welcome but not required. 
I will be merging end of week 12

2017-03-27 14:21 UTC, damithc commented on contents/projectManagement/documentation.md
> +* **Make things easier for yourself**: when you look back at your code a few months later, well-written documentation can make things a lot easier by explaining what you had been thinking when you we
Make or Makes?

2017-03-27 14:21 UTC, damithc commented on contents/projectManagement/documentation.md
> +In addition to the links mentioned above, here are the links used in the writing of this book chapter:
Instead of `book chapter`, use `document` or `article`

2017-04-24 04:57 UTC, merged