Cross Site Scripting
se-edu/learningresources pull request #4
Opened 2017-02-05 04:57 UTC by yamgent

2017-02-12 06:20 UTC, initialshl requested changes
Very clear overall structure and interesting.

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +Textboxes are commonly used in forms in websites to ask the user for input. For
Text box are two words (i think)

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +example, blog websites may provide a textbox for user to enter comments.
May change to "for the user to" or "for users to"

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +However, are they limited to just typing in plain text? For some websites, they
The "they" changed from user to website. 
Maybe more explicitly "are users limited", "Some websites do not check their input"

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +as `<b>` for bolding and `<i>` for italic.
"italicizing"?

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +The problem of not checking the user's input is when the user starts using HTML
This sentence may mean "problem is when?". Maybe "problem arises when..."

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +While any visitors of the blog will only see the non-script portion of the
The "any" seems unnecessary

2017-02-12 06:20 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +a comment. The comment gets stored in the database, and future visitors of the
May be clearer to say it is the web browser of visitors which will retrieve/load the comment

2017-02-12 11:21 UTC, initialshl requested changes
Everything else is good.

2017-02-12 11:21 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +However, are commenters limited to just typing in plain text? Some website do not
"Some websites do"

2017-02-13 12:54 UTC, initialshl approved these changes

2017-02-14 05:20 UTC, damithc requested changes
Some suggestions added

2017-02-14 05:20 UTC, damithc commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +Author: Tan Wang Leng
Link to website/resume?

2017-02-14 05:20 UTC, damithc commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +1. http://www.symantec.com/connect/blogs/cross-site-scripting-vulnerabilities
Perhaps you can distinguish between these two types of resources:
1. resources you used when writing this article: explain in what way you use each resource
2. recommended resources for the reader to learn more: explain what additional knowledge the reader can get from those resources

2017-02-14 05:20 UTC, damithc commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +However, the browser is **actually executing the script**. Therefore, the hacker
I find the introduction of the term `hacker` sudden. :-)

2017-02-15 12:50 UTC, yamgent commented
* Reworded the last paragraph of first section so that readers will know 'malicious users' = 'hackers'
* Reorganized resources such that they make more sense and briefly explained benefits of reading them.

2017-02-15 12:57 UTC, initialshl requested changes
Just need some minor edits

2017-02-15 12:57 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +1. http://projects.webappsec.org/f/WASC-TC-v2_0.pdf (page 32 & 33)
The markdown formatting here seems messed up.

2017-02-15 12:57 UTC, initialshl commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +This means that any malicious users (i.e. hackers) can write a script on their comments, such that everyone that visits the website will have the script executed. The script can be malicious in natur
"anyone who visits" may sound better

2017-02-15 12:59 UTC, yamgent commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +1. http://projects.webappsec.org/f/WASC-TC-v2_0.pdf (page 32 & 33)
:/ appeared fine on my computer lol... thanks for the heads up!

2017-02-16 00:00 UTC, initialshl approved these changes

2017-03-25 13:48 UTC, damithc reviewed
Good work @yamgent 
Some comments added. Revise as you see fit.
Adding more content and/or getting more peer reviews is welcome but not required. 
I will be merging end of week 12

2017-03-25 13:48 UTC, damithc commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +the website, that is not intended by the original website developer.
Perhaps a mention of how the name `cross site scripting` matches what it refers to.

2017-03-25 13:48 UTC, damithc commented on contents/security/crossSiteScripting/crossSiteScripting.md
> +`https://www.ecard.com/view-ecard.php?content=Happy%20Holidays<script>...</script>`
An example of how this can be used?

2017-04-24 03:32 UTC, merged