Intro to Computer Vision
se-edu/learningresources pull request #52
Opened 2018-03-23 07:41 UTC by bqnguyen94

Ongoing.

2018-04-02 15:39 UTC, bqnguyen94 commented
@se-edu/learningresources-authors can someone help me review this? Thanks alot!

2018-04-02 16:01 UTC, tran-tien-dat commented
Hi Bảo. I found your chapter touching on many interesting applications of Computer Vision, but it's a bit disappointing that it's just "touch and go" like the first few slides in the first lecture of a Computer Vision module. Personally I would like to see something more technical

2018-04-04 19:08 UTC, bqnguyen94 commented
@tran-tien-dat I added some code examples. Lmk what you think!

2018-04-04 20:10 UTC, tran-tien-dat reviewed
I'm still not very satisfied with the format of the book chapter. As I have said in my previous review but probably did not elaborate enough, overall it feels like the first few slides in a course - those slides that are supposed to WOW the students, showing that these things are so cool and interesting, but not delivering any examinable content. This can be seen by the fact that:

- The book chapter mentions a lot of complex-sounding names of algorithms or acronyms, which to a non-expert reader are just noises.
- It is also scattered with many general facts like "machines can now surpass humans in detecting objects", "machines can now detect motions in real time".
- The example codes you added are basically saying: we'll use this method in OpenCV to do the task. So after reading your book chapter, I have learnt that a computer program (and now with the examples you added, OpenCV more specifically) can transform warpped images, can classify images, can detect objects, can detect motions. So the main thing that I know is the fact that these things can be done. And then at the end, I know that if I am interested, I should go and learn Python/C++/Java and some online courses, with links provided.

Another analogy is that the book chapter feels like a wikipedia entry for non-technical reader, explaining what the field can do and historical aspects like achievements/breakthroughs of the field, rather than the technical side. Maybe this is the intention of the book chapter. I just find it... unsatisfactory as compared to other book chapters, e.g. this one https://github.com/se-edu/learningresources/blob/a59dbf93cb71a159f71a16d8ab87499ef8ba7234/contents/ai/ml.md by Alex about Machine Learning, which is related to Computer Vision as well. After reading it, I feel like I've learnt something about some ideas in Machine Learning as well as the overall process of building a machine learning system. Or like Li Hao's chapter about Rust https://github.com/se-edu/learningresources/pull/55/files?short_path=abec134#diff-abec134feeda8c298eb7d8e590e2b31f, there aren't any examples of Rust codes, but instead he provides high-level *technical analysis* of the language.

Maybe I am too biased on seeing some technical content. I think you should ask another reviewer to give their thoughts.

2018-04-04 20:10 UTC, tran-tien-dat commented on contents/computerVision/cv.md
> +First of all, we need to have the coordinates of the 4 corners of the screen. This can be entered by hand, as OpenCV has helper functions for capturing mouse input. See more [here](https://docs.openc
This sentence `This can be entered by hand, as OpenCV has helper functions for capturing mouse input` is not very clear in my opinion. What's the main message that you want to convey with it? Is it the fact that OpenCV supports capturing mouse input or is it the method of getting the coordinates. From a reader perspective, I find the 2nd information more helpful, and would prefer something like `This can be entered manually, i.e. the user can click on the 4 corners of the image and our program will capture the coordinates of the clicked points`.

2018-04-04 20:27 UTC, leeyh20 commented
About technical information, see Prof Damith's comments on my PR https://github.com/se-edu/learningresources/pull/41. Thus maybe the intention of the book chapter is to provide a reason why the reader needs to learn more about the topic.

2018-04-05 03:18 UTC, bqnguyen94 commented
@tran-tien-dat thanks for your feedback! I tried to organise the content from the view point of an outsider who may have some programming experience. I felt there are 2 types of audience here, one who wants to both gain theoretical knowledge of the topic and its many different algorithms/techniques, and how to apply them, and another who just wants to have enough conceptual information for them to dive straight into making real applications. So I only mentioned important algorithms/techniques by name and link the relevant articles for those who are interested to learn more, as it is important to be able to at least recognise them even for those who just want to write working CV code.

2018-04-05 03:21 UTC, bqnguyen94 commented
@leeyh20 do you think this chapter is convincing enough? And how can I improve on it?

2018-04-05 03:24 UTC, bqnguyen94 commented on contents/computerVision/cv.md
> +First of all, we need to have the coordinates of the 4 corners of the screen. This can be entered by hand, as OpenCV has helper functions for capturing mouse input. See more [here](https://docs.openc
👍

2018-04-06 17:26 UTC, bqnguyen94 commented
@damithc can you help me review this?

2018-04-07 12:04 UTC, damithc requested changes
No major issues. Good work 👍 
Some minor changes suggested.

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +Computer vision (CV) is a field of study of computer science concerning with the theories and technologies in building computer systems that can derive useful information from visual data. CV is a pr
Give an example of such a problem?

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +Supposed we have the picture of the Gameboy on the left, and we want to crop out just the game screen like the right side of the picture above. Notice that on the left the screen is slightly skewed,
Suppose

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +In this example, we use OpenCV and a pre-trained image classification model called the GoogLeNet. Refer to GoogLeNet's original paper [here](https://www.cs.unc.edu/~wliu/papers/GoogLeNet.pdf). The go
May be put the paper info in references (and cite from main text) rather than in the main text itself?

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +In this example, we apply object detection to find cats lurking in a given image using a Haar feature-based cascade classifier for face of cats. Haar cascade is a fast, efficient, and somewhat restri
Another place where paper info can be moved to references.

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +[Java Tutorial](https://www.tutorialspoint.com/java/index.htm)
Make these three a bullet list?

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +**Computer vision:**
It's a bit odd to see this sub heading in the middle of the paragraph. No harm removing it.

2018-04-07 12:04 UTC, damithc commented on contents/computerVision/cv.md
> +**Computer vision:**
In fact, you can tweak this whole section to present it as three steps:
>First, ... {programming}
>Next, you can ... {linear algebra}
>After that, ... {cv}

2018-04-07 14:58 UTC, bqnguyen94 commented
@damithc I made changes as requested 👍

2018-04-08 01:25 UTC, damithc approved these changes
LGTM 👍

2018-04-08 01:25 UTC, merged