Performance: memory management
se-edu/learningresources pull request #53
Opened 2018-04-03 08:08 UTC by Crphang

2018-04-04 10:53 UTC, tshradheya requested changes
Looks great overall.
Minor changes requeested

2018-04-04 10:53 UTC, tshradheya commented on contents/performance/Performance.md
> +- Using generators to reduce memory used. [Generators](https://en.wikipedia.org/wiki/Generator_(computer_programming)) are functions that generates a sequence of values. Instead of returning an expli
`[greatly reduced memory usage](https://letstalkdata.com/2015/05/how-to-use-python-generators-to-save-memory/) ` -> `greatly [reduce memory usage](https://letstalkdata.com/2015/05/how-to-use-python-generators-to-save-memory/)`

2018-04-04 10:53 UTC, tshradheya commented on contents/performance/Performance.md
> +Memory management is important for performance optimization for Computer systems. One of the common techniques in [algorithms optimisation](#using-appropriate-data-structures-and-algorithms) is space
Possible to explain `Thrashing` here in short?
It quite doesn't make  sense to link it when the sentence only makes sense if that term is known

2018-04-04 10:53 UTC, tshradheya commented on contents/performance/Performance.md
> +
Delete this line so that the code snippet is indented at same level of bullet

2018-04-04 10:53 UTC, tshradheya commented on contents/performance/Performance.md
> +- Sometimes memory usage of your program remains high because the unnecessary variables are yet to be freed from memory. If you are using a garbage collected language like Java, consider [tuning](htt
shown below`:`   ?

2018-04-04 10:53 UTC, tshradheya commented on contents/performance/Performance.md
> +- Using appropriate variable types can also offer memory usage improvement. For example, we should prefer to use primitive `int` over `Integer` to reduce the overhead introduce by the `Integer` Objec
`proposes`

2018-04-04 13:09 UTC, Crphang commented
@tshradheya Thank you so much for the review. I've added the requested changes!

2018-04-04 13:11 UTC, tshradheya approved these changes
LGTM

2018-04-04 15:34 UTC, Crphang commented
@damithc Ready for Review!

2018-04-05 08:46 UTC, damithc requested changes
Some cosmetic changes suggested.

2018-04-05 08:46 UTC, damithc commented on contents/performance/Performance.md
> +## Memory Management
To match with the previous heading, this should be `Managing Memory Usage` (or something like that?)

2018-04-05 08:46 UTC, damithc commented on contents/performance/Performance.md
>  * Using Cache Friendly codes
Line 19 says `2 techniques` but you have added a 3rd

2018-04-05 08:46 UTC, damithc commented on contents/performance/Performance.md
> +Memory management is important for performance optimization for Computer systems. One of the common techniques in [algorithms optimisation](#using-appropriate-data-structures-and-algorithms) is space
Let's use American spelling: `optimization`

2018-04-05 08:46 UTC, damithc commented on contents/performance/Performance.md
> +If you have ascertain that your system has memory related performance concerns, there are various solutions that you can employ to resolve them.
ascertained ? You can also rephrase this sentence to be simpler.

2018-04-05 08:46 UTC, damithc commented on contents/performance/Performance.md
>  * Using Cache Friendly codes
Line 23 say `codes` but the actual heading says `code`.

2018-04-06 07:47 UTC, Crphang commented
@damithc Changes added. Ready for review.

2018-04-06 09:13 UTC, damithc approved these changes

2018-04-06 09:20 UTC, merged