[WIP] Introduction to Cryptography
se-edu/learningresources pull request #6
Opened 2017-02-06 13:48 UTC by Neurrone

Tentitive outline:

* symmetric key encryption
	* Stream ciphers
	* Block ciphers
* asymmetric key encryption
	* RSA, PKI, https
* integrity:
	* hash functions
	* signitures
* interesting applications

2017-02-16 10:30 UTC, ablyx commented
I think you can reorder your work. Consider introducing stream ciphers, how they work, then talk about one-time-pad which sounds like a more specific type of stream cipher

2017-02-16 12:00 UTC, Neurrone commented
@ablyx chronologically, the one-time pad was invented first, and its impracticality inspired stream ciphers. Its also usually taught before stream ciphers. Thought one-time pad would also be easier to explain/understand first, since its simpler - the keystream is from a truly random source, each bit xored with bits of the plaintext. Do you find the reverse order easier?

2017-02-16 14:28 UTC, ablyx commented
Oh, I learnt stream ciphers first. But I think no matter the order, it would be good to explain the idea of a cryptosystem first. (Plaintext, ciphertext, key, encryption, decryption) [you can just give the main idea here]. Then talk about how the key is generated and used to encrypt and decrypt in stream cipher/one time pad. And I think one of the bigger limitation of the stream cipher is the periodicity of the stream.

2017-02-18 05:56 UTC, MightyCupcakes reviewed
Overall good job in explaining a highly technical topic by abstracting the details away.

2017-02-18 05:56 UTC, MightyCupcakes commented on contents/security/cryptography.md
> +Understanding cryptography wwill enable you to correctly use cryptography libraries and combine cryptographic primitives to match the security needs of your application.
`wwill` -> `will`

2017-02-18 05:56 UTC, MightyCupcakes commented on contents/security/cryptography.md
> +Modern cryptography involves developing methods to achieve the following:
`Modern cryptography techniques involves developing methods to achieve the following objectives` ?

2017-02-18 05:56 UTC, MightyCupcakes commented on contents/security/cryptography.md
> +Unfortunately, Shannon proved that any cipher that achieves perfect secrecy has the following limitations, making them [impractical](https://www.schneier.com/crypto-gram/archives/2002/1015.html#7).
Shannon? Might want a link to his page

2017-02-18 05:56 UTC, MightyCupcakes commented on contents/security/cryptography.md
> +* Confusion: an operation wwhich obscures the relationship between key and ciphertext. This is usually done by substitution.
`wwhich` -> `which

2017-02-18 06:55 UTC, Neurrone commented
Thanks @MightyCupcakes for the suggestions and catching the typos :)

2017-02-18 06:56 UTC, ablyx requested changes
some minor changes to be made

2017-02-18 06:56 UTC, ablyx commented on contents/security/cryptography.md
> +In practice, we do not require perfect secrecy, since attackers have limited computational power. Hence, all other ciphers are only secure against such attackers.
try rephrasing "Hence, all other ciphers are only secure against such attackers." it's a bit confusing

2017-02-18 06:56 UTC, ablyx commented on contents/security/cryptography.md
> +Unfortunately, Shannon proved that any cipher that achieves perfect secrecy has the following limitations, making them [impractical](https://www.schneier.com/crypto-gram/archives/2002/1015.html#7).
maybe you should introduce Shannon

2017-02-18 06:56 UTC, ablyx commented on contents/security/cryptography.md
> +[RC4](https://en.wikipedia.org/wiki/RC4) is the most widely used stream cipher. Though its use is now discouraged. The [eSTREAM project](http://www.ecrypt.eu.org/stream/) is a research effort to deve
why is usage of RC4 discouraged?

2017-02-18 06:56 UTC, ablyx commented on contents/security/cryptography.md
> +* The Advanced Encryption Standard (AES) is the most popular symmetric cipher today. It is used by the US government, many protocols such as TLS, WPA2-AES and SSH. This [article](https://graquantum.c
`It is used by the US government, many protocols such as TLS, WPA2-AES and SSH` I dont understand the comma

2017-02-18 07:23 UTC, Neurrone commented
@ablyx changes made.

2017-02-18 15:21 UTC, ablyx approved these changes

2017-02-18 15:51 UTC, MightyCupcakes approved these changes

2017-03-25 14:44 UTC, damithc reviewed
Good work @Neurrone 
Some comments added. Revise as you see fit.
Adding more content and/or getting more peer reviews is welcome but not required. 
I will be merging end of week 12

2017-03-25 14:44 UTC, damithc commented on contents/security/cryptography.md
> +* [Understanding Cryptography: A Textbook for Students and Practitioners](https://www.amazon.com/Understanding-Cryptography-Textbook-Students-Practitioners/dp/3642041000) is an outstanding introducto
Perhaps not refer to NUS as this is supposed to be a resource beyond NUS?

2017-04-07 14:26 UTC, Neurrone commented
@boxin-yang I've just added a short section on asymmetric cryptography and RSA.

2017-04-18 15:02 UTC, boxin-yang commented
@Neurrone  Thx for the update. I will cite your book chapter as well as some other online sources :)

2017-04-24 06:35 UTC, damithc commented
Merged via 97d8ca89ce3aa18b1629b63fec2f349d9eea697a

2017-04-24 06:35 UTC, closed without merging