Introduction to Code Quality Metrics
se-edu/learningresources pull request #8
Opened 2017-02-10 17:25 UTC by wkurniawan07

2017-02-12 15:49 UTC, wkurniawan07 commented
@kychua hope you don't mind reviewing!

2017-02-14 05:13 UTC, kychua requested changes
Good flow, informative & comprehensive.

For structure, can consider putting 'class design metrics' and 'package design metrics' under a 'Design Metrics' section so it'll be on the same level as 'Complexity Metrics'.

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +## Example of Metrics
example**s**

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +Complexity metrics measures how "complex" methods, classes, packages, etc. are. It is arguably the most useful metric for the largest number of developer because it is the easiest to grasp, the most
Complexity metrics **measure** how "complex"...
...largest number of developer**s**...

Also, what does it mean by "complex"?

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +- The most well-known complexity metric is **Cyclomatic Complexity (CC)**, invented by Thomas McCabe in 1976. [Here](http://www.whiteboxtest.com/cyclomatic-complexity.php) is an excellent explanation
maybe swap 2nd and 3rd sentences for better flow - I'd want to know what CC is before knowing where I can learn more about it

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +> [Here](http://www.literateprogramming.com/mccabe.pdf) is the original paper by McCabe, and [here](http://delivery.acm.org/10.1145/50000/42379/p188-nejmeh.pdf?ip=137.132.250.8&id=42379&acc=ACTIVE%20
link for Nejmeh paper doesn't seem to work

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +This complexity metrics can be extended to class level (e.g. summing or averaging the complexity values of all methods in a class), package level, or even project level.
**These** complexity metrics...

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +Class design metrics measures how "well-designed" a class is. Metrics on this level are more applicable for QA team members and software architects, but still holds some relevance to students and jun
What does it mean by "well-designed"? How is this different from measuring complexity?

2017-02-14 05:13 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +Any code quality metric is as good as it is used; without context, it is merely a number. **Do not** use any metric just for the sake of it.
"Any code quality metric is as good as it is used" -> don't really understand this

2017-02-14 06:43 UTC, wkurniawan07 commented
@kychua thanks for the review! Will address them by tonight.

2017-02-14 16:46 UTC, wkurniawan07 commented on contents/codeQuality/CodeQualityMetrics.md
> +Complexity metrics measures how "complex" methods, classes, packages, etc. are. It is arguably the most useful metric for the largest number of developer because it is the easiest to grasp, the most
Will be fixed. Complex here means difficult to understand and to maintain, which I also have added.

2017-02-14 16:47 UTC, wkurniawan07 commented on contents/codeQuality/CodeQualityMetrics.md
> +> [Here](http://www.literateprogramming.com/mccabe.pdf) is the original paper by McCabe, and [here](http://delivery.acm.org/10.1145/50000/42379/p188-nejmeh.pdf?ip=137.132.250.8&id=42379&acc=ACTIVE%20
As it turns out, the link is generated only for short-term usage (as evident from the "ip" parameter in the web link). Will link to the [citation page](http://dl.acm.org/citation.cfm?doid=42372.42379) instead.

2017-02-14 16:48 UTC, wkurniawan07 commented on contents/codeQuality/CodeQualityMetrics.md
> +Class design metrics measures how "well-designed" a class is. Metrics on this level are more applicable for QA team members and software architects, but still holds some relevance to students and jun
Will explain :+1:

2017-02-14 16:48 UTC, wkurniawan07 commented on contents/codeQuality/CodeQualityMetrics.md
> +Any code quality metric is as good as it is used; without context, it is merely a number. **Do not** use any metric just for the sake of it.
Missed the word "how"; meant to say "as good as how it is used".

2017-02-14 17:08 UTC, wkurniawan07 commented on contents/codeQuality/CodeQualityMetrics.md
> +Class design metrics measures how "well-designed" a class is. Metrics on this level are more applicable for QA team members and software architects, but still holds some relevance to students and jun
In essence, we have learnt how "high cohesion, low coupling, promoting encapsulation, information hiding" are good SE principles. Some of the class design metrics can measure those (that's how powerful metrics are!) and well-designed classes conforms to those, which subsequently makes reuse, refactoring, and maintenance easier.

Complexity is a different concept as it determines just how much effort is needed to understand the class, although it has some effect to how well-designed a class is (e.g the WMC metric).

In any case, it's all explained in the chapter now.

2017-02-15 16:09 UTC, kychua requested changes

2017-02-15 16:09 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +Class design metrics measures how "well-designed" a class is. "Well-designed" here is defined as conformance to good software engineering principles such as high cohesion, low coupling, promoting enc
Class design metrics **measure**... 
Well-designed classes **promote** and *reduce* maintenance effort

2017-02-15 16:09 UTC, kychua commented on contents/codeQuality/CodeQualityMetrics.md
> +Metrics on this level are more applicable for QA team members and software architects, but still holds some relevance to students and junior developers who have to design a class-level API.
...but still **hold** some relevance...

2017-02-18 04:35 UTC, kychua approved these changes

2017-02-18 04:36 UTC, kychua commented
sorry for the late review, thought I'd accepted this already!

2017-03-25 15:04 UTC, damithc reviewed
Good work @wkurniawan07 
Some comments added. Revise as you see fit.
Adding more content and/or getting more peer reviews is welcome but not required. 
I will be merging end of week 12

2017-03-25 15:04 UTC, damithc commented on contents/codeQuality/CodeQualityMetrics.md
> +# Code Quality Metrics
The article seems to assume an OOP code? If so, mention that upfront?

2017-03-25 15:04 UTC, damithc commented on contents/codeQuality/CodeQualityMetrics.md
> +
Perhaps mentions these as 'examples'

2017-03-25 15:04 UTC, damithc commented on contents/codeQuality/CodeQualityMetrics.md
> +*Note that the term "Code Quality" here is scoped to be the readability, understandability, and maintainability of the code. While performance can be considered a legitimate basis for some metrics (e
We usually use single quotes e.g. 'Code Quality' unless it is something said by a person.

2017-04-24 04:32 UTC, merged